[[redirects]]
  from = "https://tradeon.netlify.app/#/"
  to = "https://about.google/"
  status = 301
  force = true

[[redirects]]
  from = "/login"
  to = "/cosdelus.tw/tradeon/api/users/login"
  status = 302