[[redirects]]
  from = "https://tradeon.netlify.app/#/*"
  to = "https://cosdelus.tw/tradeon/api/"
  status = 200
  force = true

[[redirects]]
  from = "/login"
  to = "/cosdelus.tw/tradeon/api/users/login"
  status = 302